//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzychodniaPOZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WizytaLekarz
    {
        public int IdWizytaLekarz { get; set; }
        public int IdLekarz { get; set; }
        public Nullable<int> IdPacjent { get; set; }
        public int IdSpecjalizacja { get; set; }
        public System.DateTime DataWizyty { get; set; }
        public System.TimeSpan GodzinaWizyty { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Lekarz Lekarz { get; set; }
        public virtual Pacjent Pacjent { get; set; }
        public virtual Specjalizacja Specjalizacja { get; set; }
    }
}
